#!/usr/bin/env ruby

require "solidarity"

# TODO: Add option parsing (e.g., using OptionParser)

project_path = ARGV[0]

unless project_path
  warn "Usage: #{File.basename($PROGRAM_NAME)} <path_to_ruby_project>"
  exit 1
end

begin
  graph = Solidarity::RailRoadyRunner.run(project_path)
  solid_results = Solidarity::SolidEvaluator.new(graph).evaluate_all
  report = Solidarity::Reporter.generate_report(solid_results)
  puts report
rescue => e
  warn "Error: #{e.message}"
  exit 1
end
